### ISSUE TITLE
Migration to new domain model

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#142]
As we agreed somewhat on the new domain model based on this [DB schema](https://github.com/redhat-ipaas/ipaas-rest/blob/master/docs/database/schema.png) but still want to support view specific response objects (e.g. like a `Connector` with all its `Action`s in one case, only `Connector`s with no `Action` references in other cases) to remove efforts from the client side, I suggest the following rough migration strategy for the next sprint:

* The `model` module currently holds the "old" domain model, whose objects are directly returned to the client. The content of this model moves to the `rest` module and serves as the initial view objects. This means, that the client in this first step needs not to be changed.
* The domain model from #135 is moved into the `model` module.
* A custom mapping from view to domain needs to be added in the `rest` module. As the concepts are (hopefully) quite similar, this shouldn't be that hard. If we detect that it would be easier to change one of the view objects instead of a complicate mapping and if the client would benefit from this (because of a better consumable structure), we should then adapt the VOs and client instead.
* An additional `jpa` module can provide an alternative implementation of the interfaces in `dao`. This should be straight forward.

The advantage of this approach is that we can adapt the view layer incrementally for the client without doing a big bang where everything needs to be changed synchronously.

Does this makes sense or are there better alternative approaches ?

Comments are highly welcome ;-)

**Comment by KurtStam** [comment]
OK I will a PR for the first two items
1. move whatever is in `model` back to rest.
2. use the `model` module to park the jpa entities.

Does that make sense? This shouldn't break anything.

**Comment by rhuss** [comment]
This would work technically right now, but would introduce a dependency from dao -> rest as 
we for the moment would still use the old domain objects in the DAO layer.
This is then also a circular dependency (as we obviously have a dep from rest -> dao).

But you could introduce a "model2" and a "jpa" where we later rename "model2" to "model" and move the content of model to "rest".

So both approaches would work, guess its not a big problem to have the bogus deps for a temporary time.

The more difficult part will be the mapping between view objects and domain objects, which should happen in "rest", too.

**Comment by KurtStam** [comment]
Model2 was introduced. We now need to refactoring to start using it.

**Comment by rhuss** [comment]
@KurtStam imo i see the following tasks to do:

- [ ] Change *dao* to use *model2* object in their interfaces
- [ ] Adapt *jsondb* to fit these new dao interfaces
- [ ] Move the content of *model* as a subpackage of *rest*. The rest interfaces stay the same
- [ ] Add a mapping in *rest* from the (former) *model* object to the *model2* objects. That's the hardest part.
- [ ] Introduce a *jpa* module implementing *dao*

At the end *model2* module should then be renamed to *model*.
