### ISSUE TITLE
Change Integration management to async

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#161]
Creating / updating intgeration involves expensive operations like github and openshift object creations. Currently this is done blocking, which leads obviously to various problems (including timeouts from the OpenShift router)

This should be fixed by:

* Decouple integration REST calls from the actual backend handling by an async event mechanism.
* Introduce status in an `Integration` object recording the steps in the linear workflow (create github repo, store files, create webhook, create build config, build).
* Think about compensation actions of previous steps if a step fails.

The UI needs to be adapted to show the status somewhere which on status change should be pushed from the server.

**Comment by chirino** [comment]
Using a status field on the integration should work wonderfully since the UI is currently being notified (via WebSocket or SSE event) whenever an entity is updated.

**Comment by KurtStam** [comment]
@chirino, we have two fields StatusType and StatusPhase:
This is so we can activate an integration by setting the StatusType to "Activated" on the integration.
When deployment starts it then sets the StatusPhase to Pending, and when up to Running, when not up to Failed, when successfully deactivated to Succeeded. There is also an Unknown Phase just in case. We could add a StatusMessage to report errors.

**Comment by KurtStam** [comment]
Work on this is ongoing on PR https://github.com/redhat-ipaas/ipaas-rest/pull/262 and https://github.com/redhat-ipaas/ipaas-rest/pull/236
