### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by jimmidyson** [syndesisio/syndesis-rest#20]
Re discussion in https://github.com/redhat-ipaas/ipaas-api-java/pull/19#discussion_r91928245 we should settle on a code style that we can all adopt to ensure that PRs are easier to review (formatting changes not muddying the changes for review).

We have to remember that not everyone uses the same editor (although of course IntelliJ is the best for Java ;)).

And we probably need to have an automated check for PRs so that we can enforce the code style.

**Comment by jimmidyson** [comment]
[Spotless](https://github.com/diffplug/spotless) seems like a great project & 3.x will have a Maven plugin available - https://github.com/diffplug/spotless/tree/3.x/plugin-maven. Might try to use this from SNAPSHOTs repo.

I also like the idea of reusing a previously defined Java style like https://github.com/google/google-java-format which also has an intellij plugin so easy to share, with no configuration, etc (no decisions to make, no discussion to have - yay!).

**Comment by jimmidyson** [comment]
No spotless is too immature for now. But I've found https://github.com/talios/googleformatter-maven-plugin which works pretty well.

Anyone have any strong feelings not to follow google java style? See https://google.github.io/styleguide/javaguide.html. Opinionated of course, not configurable (which I like - nothing worse than wasting time arguing about tabs vs spaces, braces on new line, etc).

The Maven plugin formats files so we can run this only on CI or as part of the build locally (my preference). The intellij plugin, https://plugins.jetbrains.com/plugin/8527, works fine too.

Comments?

**Comment by jimmidyson** [comment]
I'm such a huge fan of gofmt & rustfmt - this feels really close to it imo.

**Comment by zregvart** [comment]
Also see #377
