### ISSUE TITLE
Add a "verifierAction" reference to a Connector

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#219]
This issue is a reminder, that we have to deal with the mismatch where the verification happens in the iPaaS and the Camel world:

* In *iPaaS* the verification of a `ConfiguredConnector` (aka _connection_) is done by the _expert developer_ when he enters the (technical) connection information. It's before a _citizen developer_ can select an `Action`.
* For Camel verification happens on the  camel-connectors ("twitter-mention"). This is an iPaaS `Action` which is not yet selected when the verification is supposed to happen.

One solution without touching Camel is to mark a specific `Action` as the `verifierAction` which is referenced by a `Connector` and use in the verification process. This of course works only if **all** `Actions` belonging to the same `Connector` have the same verification logic.

Alternatively, instead of reusing an existing `Action`, one could introduce a dedicated `VerificationAction` which has no business meaning except the verification of the connection parameters.

Are there other, better, solutions ?

**Comment by rhuss** [comment]
Another idea could be to group all similar Camel connectors into single jar instead of having one jar per connector. The manifests could be added with a dir structure like 

```
META-INF/
  services/
     org.camel.Verifier     <-- this is a "standard" Java ServiceLoader class used for the verification 
  camel-connectors/
     http-get.json
     http-post.json
```

and then called `http-connectors.jar`. Might be a bit far fetched and might not fit into the Camel model (sorry, when I'm ignorant here, have too less of a clue ;-) but for iPaaS verification this would be awesome (since we have a single verifier for a group of similar connectors), and would also reduce a bit the granularity (i'm a bit afraid of Maven artefact and module 'explosion')

Just an idea ....

**Comment by chirino** [comment]
I do like the idea of putting all related connectors into a single jar.  Keep in mind we will need to eventually implement a UI which creates connectors and part of that is going to be defining actions, etc.  For all connectors I can think about, they are all based on the same camel component, it's just mostly extra meta data you need to add for each action that it supports.

And for projects like Salesforce where you need to generate a model, it makes sense to share that model across all the actions.  Yeah we could do multi module projects to handle those cases, but that seems much more complex than a single jar for a connector.
