### ISSUE TITLE
How to handle OAuth tokens that expire

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#248]
I know, Twitter currently [does not expire](https://dev.twitter.com/oauth/overview/faq). However, I opened the issue because I think there will be connectors (facebook, google) with expiring tokens and I wonder how we should deal with the refreshment process (as well with a smoother OAuth UI flow).

And also as a reminder to keep you clocks in sync otherwise things like this can happen:

```json
[
  {
    "scope": "PARAMETERS",
    "status": "OK"
  },
  {
    "scope": "CONNECTIVITY",
    "status": "ERROR",
    "errors": [
      {
        "code": "401",
        "description": "Timestamp out of bounds.",
        "parameters": [],
        "attributes": {
          "error.type": "http",
          "http.text": "Timestamp out of bounds.",
          "twitter.exception.code": "ec1fe56d-20c5d940",
          "twitter.exception.message": "401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.\nmessage - Timestamp out of bounds.\ncode - 135\n",
          "http.code": 401,
          "twitter.error.code": 135,
          "twitter.status.code": 401
        }
      }
    ]
  }
]
```

**Comment by zregvart** [comment]
With Salesforce we can use [OAuth 2.0 JWT Bearer Token Flow](https://help.salesforce.com/articleView?id=remoteaccess_oauth_jwt_flow.htm&type=0) that allows the client to use a self-signed certificate. So the expiration of the token can be controlled by the client. I think whenever possible this should be the connector's (component's) responsibility.
