### ISSUE TITLE
Sending an object with null values to /validator results in an HTTP 500

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#257]
If I just send a POST to /v1/connectors/twitter/validator with:

```
{
  "accessToken": null,
  "accessTokenSecret": null,
  "consumerKey": null,
  "consumerSecret": null
}
```

I get back an HTTP 500.  This would be the equivalent of just hitting the validate button straightaway in the create connection flow before filling in any fields.

**Comment by KurtStam** [comment]
@gashcrumb is this still an issue?

**Comment by gashcrumb** [comment]
I've no idea if this is even relevant any more, let's close it.
