### ISSUE TITLE
Funktion route builder is adding json:marshal steps

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-rest#367]
The funktion route builder is adding `json:marshal` steps we don't need:

<img width="1196" alt="openshift-jvm" src="https://cloud.githubusercontent.com/assets/103255/25529705/384f7214-2bf1-11e7-86c5-01eb54011da8.png">

**Comment by jimmidyson** [comment]
Took a quick look at this, expecting it to be super simple, just strip out the json:marshal steps... But then I hit the issue described in http://camel.465427.n5.nabble.com/JsonPath-stripes-quotes-during-split-td5771398.html , jsonpath splitter strips quotes from split elements.

@davsclaus That sounds like surprising behaviour to me. Any more thoughts on what we could do here? It doesn't feel right that we should always add in json:marshal steps but with this particular issue, I can't see any other option.

As one idea, as we're currently always using the jsonpath splitter, we know we're working on json so we can force the marshalling back to json I guess, as in the linked thread. This isn't going to work as the splitter becomes more complex in future though, but good enough for now I guess.

**Comment by davsclaus** [comment]
@jimmidyson good work. Yeah the json thing was something that was kinda hardcoded into funktion to make it look easy/good to do for demos where json payloads was only being used. 

How jsonpath works I have less control as its a 3rd party project. I have logged a Camel ticket (https://issues.apache.org/jira/browse/CAMEL-11558) so we can take a look at this, as I also think it should not do that. You want it easy out of the box.

**Comment by davsclaus** [comment]
@jimmidyson okay so in Camel 2.20 onwards there is a new `jsonpathWriteAsString` you can use that uses String outputs by default
https://github.com/apache/camel/blob/master/components/camel-jsonpath/src/main/docs/jsonpath-language.adoc#split-json-data-into-sub-rows-as-json

Its from this commit
https://github.com/apache/camel/commit/5aa5ef9ba796f624a1d8f8da94eaaa3bc4777bb8

**Comment by jimmidyson** [comment]
Awesome! Do we have fuse EA 2.20 builds to use for this until upstream release? Thoughts @rhuss @chirino?

**Comment by davsclaus** [comment]
I dont know about EA builds but the Fuse team are doing some fuse 7 kits which I assume is tracking upstream Apache Camel master branch.

**Comment by jimmidyson** [comment]
@janstey Hey! Do we have regular Camel 2.20 EA builds externally accessible for syndesis to use?
