### ISSUE TITLE
Proposal: Failed state for Integrations

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-rest#371]
Currently, it seems that there's no `Failed` state reported back if e.g. user create Integration with non-existent Connector(Maven dep. missing etc.). Therefore Integration is stuck in endless loop on `In Progress`. 

Same principal may apply if user reaches deployment quota in OpenShift and new deployment can't be created anymore.

There's should be a mechanism (with built-in timeout) that reports back if Integration deployment failed for various reasons (quota reached, missing dependency in Maven, etc.)

**Comment by rhuss** [comment]
Completely agree. We should reconsider the whole state workflow and define the possible transitions among them (best explained with a diagram).

See also #323 how error currently is handled: Having a non-null status message means to be in the UI state 'error' .

**Comment by jimmidyson** [comment]
This should be handled by a full review of our backend. I'm starting to write some stuff up, but slow going for now... hope to have something for review ready for implementation in next few days.
