### ISSUE TITLE
Create Camel Component for Twitter (keyword) Search

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis-rest#384]
Part of https://issues.jboss.org/browse/IPAAS-321 to add support for Twitter Search:

1. Add Camel Component
2. Update the Twitter Search MetaData for TwitterSearch

**Comment by KurtStam** [comment]
@jimmidyson @davsclaus the twitter connector is using the same field for keyword search as for 'complex search'. 

see https://github.com/KurtStam/camel/blob/master/connectors/examples/twitter-search-connector/src/main/resources/camel-connector-schema.json#L27 which is a problem if we want to build a widget as the widget will think ‘string’ and we really want ‘array’. Do we need two connectors if we want to do that, or should we spilt this up into two fields (keywords: array, complex search: string)?

**Comment by davsclaus** [comment]
Just separate the words with comma, eg to search for dog or cat

     keywords=dog,cat

**Comment by KurtStam** [comment]
@davsclaus Yes, but remember the UI builds a widget based on the data type. So for keywords we'd like to see a widget that adds keywords.

**Comment by davsclaus** [comment]
Why not let the citizen user just use a comma. The twitter client on their mobile phone don't have a widget with +/- to add/remove rows to make searching tweets with multiple keywords, they just use comma today.
   
    https://twitter.com/search?q=dog%2Ccat&src=typd
![screen shot 2017-06-05 at 16 40 49](https://cloud.githubusercontent.com/assets/477100/26788525/c305a592-4a0d-11e7-8b30-082e9e5cdfcc.png)

**Comment by davsclaus** [comment]
Anyway from Camel pov, it does not matter how you build the UI, just that the information you feed into Camel is in one option, `keywords=dog,cat`

**Comment by KurtStam** [comment]
@davsclaus can the twitter connector transform array of strings a comma separated string before handing it to the camel component?

**Comment by davsclaus** [comment]
No that is not possible.

As you can see from that camel-connector-schema file each of those row has one value only, not a dynamic array of values.

**Comment by KurtStam** [comment]
@davsclaus ok so the only way yo address this then is to create a second field that takes an array in the camel component, and create a second connector that references this field in the camel-connector-schema.

**Comment by davsclaus** [comment]
No these options cannot really support an array you can specify. Mind that Camel is most often configured in camel uri's, where you use key=value pairs. An array in that format would then be either as we do by using comma as separator, or allow to duplicate the key=value pairs. 

So you do

    keywords=dog&keyword=cat

This kind is not really supported in Camel, but a variation where you can use dynamic names with a prefix, eg

    something.foo=123&something.bar=456

In this example something is the prefix, which has been marked as multi valued.

    @UriParam(label = "advanced", prefix = "something.", multiValue = true)

But this is really for advanced stuff where you configured some Java POJO with dynamic option names. 

I suggest to let go of this and move on, and just use a single option for the keywords now - especially since it can already do multiple keywords separated by comma which is what twitter also supports. There are bigger fish to fry, and most users will only need to search for a single keyword anyway.

**Comment by KurtStam** [comment]
ok @davsclaus, thx :)

**Comment by davsclaus** [comment]
A workaround would be to add some fields on the connector and add extra code there where you merge those fields together and separate them via comma so it become one field again

eg for example to support up till 3 keywords

     private String keyword1
     private String keyword2
     private String keyword3

**Comment by rhuss** [comment]
@KurtStam what is the state of this issue? Is it implemented ?

**Comment by KurtStam** [comment]
@rhuss It's implemented but ATM it needs release of both Camel and Connectors

**Comment by aileenc** [comment]
How do we get a new release on Camel and Connectors? Can we use the builds from Fuse 7 pipeline?

**Comment by rhuss** [comment]
@aileenc good question. For syndesisio/connectors I can trigger a release easily, but for Camel I wonder what the process it. We probably need to switch to some snapshot versions until Camel 2.20 is out (as we did pre-2.19, too) // @davsclaus @chirino

**Comment by davsclaus** [comment]
Didnt we use EA builds from fuse-camel in the past? I think the fuse-camel branch is tracking upstream Camel master branch so they should be reasonable up to date.

And wasn't there something about using SNAPSHOT from Apache Software Foundation Maven Repo was somehow blocked in the redhat network, so Jenkins could not download the SNAPSHOT jars? @jimmidyson ?

**Comment by rhuss** [comment]
ah yes, I remember now. Red Hat was (is still ?) on a black list on the Apache repos for some reason, so we can't pull from there. So we should switch back to EA builds. @chirino are the EA build set up to track Camel 2.20 ?

**Comment by rhuss** [comment]
@KurtStam can this issue be closed ? Seems that we are done with it.

**Comment by rhuss** [comment]
As the associaed PR is merged, I'm going to close this one. feel free to reopen.
