### ISSUE TITLE
Credential management and acquisition

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#386]
See: syndesisio/syndesis-ui#556

Problem:
There is a need for managing credentials (OAuth tokens, username and
passwords, certificates, private keys, ...) that are needed for a
connector to authenticate against a 3rd party resource (service,
database, queue, ...).

1/
First issue is how to store and provide connectors with appropriate
credentials.

2/
Second issue is how to obtain credentials as they can be issued by the
3rd party or require input from the user of the system.

Solution:
1/
Provide API to store and retrieve credentials that solves first issue.
This API can be queried to retrieve manage all credentials or to manage
only credentials applicable to single connector instance.
Selection of applicable credential is done via connector group name
i.e. Camel label, e.g. 'twitter'.

Proposed REST API:
credentials/{id} - manages all credentials in the system
connectors/{id}/credentials/{id} - manages credentials applicable to
single connector

2/
Provide API for information on obtaining credentials that solves part of
the second issue. This API will provide information to the UI on how to
obtain credentials (e.g. type: username/password input or link,
properties: list of properties for manual input).

Proposed REST API:
connectors/{id}/credentials/acquisition - provides the info on
obtaining the credential

3/
Provide (Java) plug-in API performing credential acquisition and
endpoint for each plugin to operate in (if needed).

Proposed REST API:
connectors/{id}/credentials/acquisition/{type}/* - endpoint for each
method of credential acquisition

Proposed (Java) plug-in API:
interface CredentialAcquisitor {
AcquisitionInfo info();
AcquisitionHandler handler(CredentialRepository);
}

Issues:
Storage of credentials -- k8s secrets?
ACL enforcement -- tie in with Keycloak?

**Comment by jludvice** [comment]
I shouldn't be able to fetch credentials from browser console like this for instance:
```js
$("#clientId")[0].value
HarQs27Qlx77A3WZU...
```
![connection](https://user-images.githubusercontent.com/8707241/27690415-93c902ba-5ce1-11e7-909e-cd54b97338ce.png)

**Comment by zregvart** [comment]
> I shouldn't be able to fetch credentials from browser console like this for instance (CC @Stefan365) :

@jludvice not saying it's not possible, but I don't think it would be as easy. Try going to https://accounts.google.com and on the password screen in development tools type `document.forms[0]['password']`. At the point of input that value is accessible via JavaScript, we can make it so that the REST API does not provide secret values back to the UI (#373).

**Comment by rhuss** [comment]
PR is merged, closing this issue.
