### ISSUE TITLE
Include used Funktion functionality directly in Syndesis

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#389]
We are using only a small fraction of Funktion so in order to reduce maintainability efforts, we are including only this small part directly into Syndesis.

**Comment by jimmidyson** [comment]
Do we want this in a separate repository, say `syndesis-integration-runtime`?

**Comment by rhuss** [comment]
If it is used by syndesis-rest and the actual generated integration runtimes, it make sense to extract it (to avoid a dependency of the running integration in a syndesis-rest module).

**Comment by jimmidyson** [comment]
Agreed, will be in https://github.com/syndesisio/syndesis-integration-runtime

**Comment by jimmidyson** [comment]
First cut at migrating integration runtime to syndesis, stripped back as minimal as i dare for now - https://github.com/syndesisio/syndesis-integration-runtime

**Comment by rhuss** [comment]
Thanks ! I will have a deeper look early next week ...

**Comment by rhuss** [comment]
Can we close this epic for now ? Any additional tests required ?

**Comment by jimmidyson** [comment]
Nothing planned, but generally we should have more tests to check integrations actually are created and run... But I'd do that under a separate issue perhaps?

**Comment by rhuss** [comment]
Good idea. I will also add syndesis-integration-runtime to the zenhub board

**Comment by rhuss** [comment]
Issue has been finished (don't know why I reopened it)
