### ISSUE TITLE
Move from using GitHub API to normal git workflow

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#395]
At the moment we use the GitHub API, which results in one commit per file (because we are using the Github REST API). 

We need to create the Git repo locally on a volume and then push it out to GitHub. We should the way how we do it with the way how `openshiftio/launchpad-missioncontrol` does it

See https://github.com/openshiftio/launchpad-missioncontrol/tree/master/services/github-service-impl/src/main/java/io/openshift/appdev/missioncontrol/service/github as a starting point.

**Comment by KurtStam** [comment]
@rhuss So if we're no longer going to use the REST api, then what will be using for authentication to GitHub?

**Comment by rhuss** [comment]
That's a good question, and we probably should have a look how the openshift.io launchpad does it. See the link above as a starting point. It probably depends on how the library we want to use handles authentication, but it's probably also via an initial oauth flow. Let me research that a bit (but you might also want to look into the code).

@jimmidyson do you have any idea how this could work?

**Comment by KurtStam** [comment]
I think I would prefer public key authentication off possible so that it works for any git implementation. I'm going to check to see if the GitHub api supports uploading public keys.

**Comment by rhuss** [comment]
No, not yet. And I'm afraid that @kcbabo is not very keen on having the citizen user to deal with public / private key management. 

We could create a keypair on the fly though, do the upload and store the private key in the DB. If require we could let an expert user override this via the UI in the gloabl settings section. But I think this is also a story for UXD.

I think this would be a nice solution.

**Comment by KurtStam** [comment]
@rhuss that's what I was going for, creating one on the fly for the citizen user (if not already present) and overridable if needed.

**Comment by rhuss** [comment]
I think thats a good approach. We can even start without UI by doing only the automatic setup and add this later to the UI.

**Comment by rhuss** [comment]
Is it how the launchpad does it, too ? (haven't had a loook yet)

**Comment by KurtStam** [comment]
@rhuss - the code doesn't seem to deal with authentication, so maybe it assumes it's dealt with elsewhere (i.e. by using keys)

**Comment by rhuss** [comment]
@KurtStam any progress on this story ? Is there something I can help ?

**Comment by KurtStam** [comment]
@rhuss I need to help defining the requirements around this. Here are some questions for you:

1. We can use a git 'Personal Access Token' to access GitHub using jgit over HTTPS, I wrote a little prototype to test this out. I can try to hide the credential stuff so other implementations can be provided/configured (also using other git providers). Does that sound ok? 

2. I think we *know* the first time we access Git? Or do we need a test into the remote git repo to see if it exists already?

3. Can we assume the local git repo is persisted, or do we recreate with each git access? If we persist it, then where?

4. Do we have to handle access of the same repo by different users? If so, then I'm assuming they only share the remote git repo, not the local one?

5. It'd be good if we can talk about the interface, answers to the questions above will drive that and I think the current one will no longer be valid.

**Comment by rhuss** [comment]
@KurtStam before trying to answer your question, my naiive idea how think it could:

* Check via the GitHub API whether the repo exists.
* If it does not exist, create the GitHub repo via API
* Get the Git URl via the GitHub API
* Check it out locally in an empty directory
* Make your changes locally in the file system
* Local git add & commit
* Git push
* Delete local directory

@jimmidyson @KurtStam is this a reasonable git workflow ?

(sorry, I was wrong yesterday that we completely ditch the GitHub API access. Actually we need it for sure to create a repository on GitHub).

@KurtStam to your questions (if they are not already answered by the workflow description above): 

> We can use a git 'Personal Access Token' to access GitHub using jgit over HTTPS, I wrote a little prototype to test this out. I can try to hide the credential stuff so other implementations can be provided/configured (also using other git providers). Does that sound ok?

Is it possible to create such an Access Token via the GitHub API ? In all cases we have to avoid that the citizen user need to create the toke out of band.

> I think we know the first time we access Git? Or do we need a test into the remote git repo to see if it exists already?

This can be infered via the GitHub API (we do this already).

> Can we assume the local git repo is persisted, or do we recreate with each git access? If we persist it, then where?

We do create each time afresh in a temporary directory. Simplifies thing quite a bit and since the creation happens async anyway its not a performance issue

> Do we have to handle access of the same repo by different users? If so, then I'm assuming they only share the remote git repo, not the local one?

Currently we assume that only the GitHub account of the current user is used. This might change later, but for now this is a safe assumption.

> It'd be good if we can talk about the interface, answers to the questions above will drive that and I think the current one will no longer be valid.

Which intreface do you refer to ? The internal interfaces in syndesis-rest ?

**Comment by KurtStam** [comment]
> Is it possible to create such an Access Token via the GitHub API ? In all cases we have to avoid that the citizen user need to create the toke out of band.
I don't think we can avoid it (we do something similar at the moment with a client_id and client_secret. I think it'd be bad to ask for their actual GitHub password. Also it'd be problem if they use two-factor authorization.

> Which intreface do you refer to ? The internal interfaces in syndesis-rest ?
The contract used to for synthesis-rest to use git(hub()

**Comment by rhuss** [comment]
@KurtStam We don't have to ask for the GitHub password as we are already authenticated via OAuth with GitHub. We just need to ask for the permission to update access tokens. The question is, whether this is covered via OAuth authorizations. @jimmidyson any idea here?

Yes, the interface can be freely adapted as it is currently used internally.

**Comment by KurtStam** [comment]
Since there is no way to NOT use the Github REST API we can use it to create a personal access token:
https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization

**Comment by rhuss** [comment]
Cool, that is exactly want we want.

**Comment by zregvart** [comment]
So I guess we can close this now?

**Comment by rhuss** [comment]
YES !
