### ISSUE TITLE
Broken Deployment and Jenkins Builds

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis-rest#398]
Upon deployment some pods do not deploy correctly and end up in a crash loop. I think a lot of people have reported this and sometimes it can fix itself. This issue affects our Jenkins build, and makes all of our builds fail. @jimmidyson @chirino @rhuss do you know why the pods don't always come up? I've been trying to fix this but I think I need some pointers on where to go look for this.

See the logs of this build:
https://github.com/syndesisio/syndesis-rest/pull/397

**Comment by rhuss** [comment]
We have fixed the initialDelaySeconds for the liveness checks which should fix this issue. @KurtStam does it still happens to you ?

**Comment by KurtStam** [comment]
Seems fixed now.
