### ISSUE TITLE
Switch to using 'configurations ' for configuring camel connectors via SB

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-rest#399]
See ref docs at:
https://github.com/apache/camel/blob/master/connectors/camel-connector/src/main/docs/connector-component.adoc

Camel SB now supports creating '... multiple instance of the connector i.e. to use different logins and this is now possible through the 'configurations' parameters'

The project generator should switch to this new config style so that you can use 2 different connections of the same connector in a single integration.

**Comment by lburgazzoli** [comment]
@chirino @rhuss 

I did start some work on this and to make it working I need to generated an unique id for the connector alias: is there any unique id associated to a Step I can reuse for such purpose ? 

A simple alternative simple solution would be to use the step index while looping over the steps so i.e. there will be ``twitter-search-1, ..., twitter-search-n``.

Then there is a prerequisite to move syndesis to camel 2.20

**Comment by lburgazzoli** [comment]
Reopen if needed
