### ISSUE TITLE
Status page via cachet?

### ISSUE THREAD

**Issue by jimmidyson** [syndesisio/syndesis-rest#40]
Having a nice status page ala https://statuspage.io would be great.

Cachet (https://cachethq.io) an open source status page system which is worth looking at (there are others).

This would be useful for you too @kahboom, @gashcrumb so we can provide status of the ipaas components on the same page (UI, REST API, storage, integration runtime, etc).

**Comment by kahboom** [comment]
I would absolutely love this.
