### ISSUE TITLE
Sync Checkstyle, Findbugs, PMD configuration with Codacy

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#417]
Currently we use Checkstyle, Findbugs and PMD default settings along with default settings from Codacy.
It should be possible to run the `checks` profile locally and have it pass or fail with the same rules as on Codacy.

**Comment by rhuss** [comment]
Not sure whether codacy rules can be mapped one to one to our rules.

However I would be happy, too, if we activate the full set of tests to the CI, too and break the build. I wonder how the reporting looks like, though. It shouldn't be the case that one would have to lookup in CI logs.

**Comment by zregvart** [comment]
From the [Codacy documentation](https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns) seems that it auto detects Checkstyle (`checkstyle.xml`), FindBugs (`findbugs.xml`) and PMD (`ruleset.xml`) would be nice if we could export the existing Codacy rules and use those, I did not find a way to do that.
All basepom checks should be active in CI (see https://github.com/syndesisio/syndesis-rest/blob/master/pom.xml#L742), which should include Checkstyle. FindBugs and PMD, we could also make them fail the build (by setting `basepom.check.fail-[checkstyle|findbugs|pmd]` to `true`.

**Comment by zregvart** [comment]
Still needs PMD rules -- the package private pattern is from PMD.

**Comment by zregvart** [comment]
This was done, closing.
