### ISSUE TITLE
Generated integration project should optionally use productized FIS bom

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-rest#418]
The project generator should support switching to using productized FIS boms in the generated pom.xml files.

**Comment by rhuss** [comment]
The benefit I guess would be to have the same version of camel libraries across all integrations, right? 

For the connectors however the versions are currently coming out of the DB, so I wonder how these would fit in the picture (and also of course, how to update connectors for deployed integrations).

**Comment by chirino** [comment]
Right. Perhaps we should avoid adding connector versions in the DB and add those to the bom??
This goes hand in hand with how do we patch ipaas integrations.

**Comment by rhuss** [comment]
I would keep this issue in mind, but first check that we get our update process straight. I guess an integration then must have least then a reference to the bom version and must have a way to either update the BOM via UI (admin area) or some automatic update which runs over all deployed integrations needs to be implemented.

**Comment by chirino** [comment]
This should also include the FMP config in the pom.xml

**Comment by lburgazzoli** [comment]
Would something like this:

```java
@Value.Immutable
public interface GenerateProjectRequest {
    enum Layout {
        FIS,
        OSS
    }

    Layout getProjectLayout();
    ...
}
```

be ok to discriminate the project layout ?

**Comment by rhuss** [comment]
I think that's perfectly fine. Maybe we call it the Layout 'REDHAT' and 'SYNDESIS' or so, because it might be used also for other dependencies used in the generated pom.xml (which for the RedHat case must only use productised dependencies, including connectors).

The layout then could be selected by a simple configuration option.

What will be also interesting is how to configure the appropriate repositories (with authentication for the redhat case ?)

**Comment by lburgazzoli** [comment]
A maybe better alternative would be to use spring-boot profiles so i.e. we can set the path of the templates and additional stuffs in each profile

**Comment by lburgazzoli** [comment]
Should we close this as it has been merged ?

**Comment by gashcrumb** [comment]
+1

**Comment by lburgazzoli** [comment]
Please reopen if needed
