### ISSUE TITLE
Add REST api to oauth client id/secret resources for the setup page

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-rest#424]

**Comment by chirino** [comment]
This should iterate the connectors to determine which require oauth client id/secrets.  We need to make sure that we can configure these properties at that connector level.

**Comment by rhuss** [comment]
Should we need this API to https://github.com/syndesisio/syndesis-project/issues/28 (which btw the proposal document has not yet started) ?

**Comment by chirino** [comment]
syndesisio/syndesis-project#28 and syndesisio/syndesis-project#13 seem like they are dups of each other no?

**Comment by rhuss** [comment]
@chirino The difference is that https://github.com/syndesisio/syndesis-project/issues/13 is the epic (user story), 28 is the creation of the design proposal (as task attached to this epic).

It is following the workflow I described in https://github.com/rhuss/syndesis.io/blob/4d1b5a284cd0e9359fb49f03ce8f48fe9e7b6004/content/community/engineering_guidelines.md#development-workflow which is currently under review.

**Comment by zregvart** [comment]
This is implemented with #442
