### ISSUE TITLE
JSONDB - streaming is probably leaky

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#427]
Is there a real need for streaming from JSONDB? I don't think the resources (Connection, PreparedStatement, ResultSet) are closed properly with streaming, for instance when Consumer drops in the middle of the stream.

see https://github.com/syndesisio/syndesis-rest/blob/fd55b6a32ecc331dd2a890c0a5c5e16eaa074522/jsondb/src/main/java/io/syndesis/jsondb/impl/SqlJsonDB.java#L116

@chirino any thoughts?

**Comment by chirino** [comment]
You don't think those finally blocks will handle closing the db resources?

**Comment by zregvart** [comment]
Yeah sorry, middle of the stream is probably not the issue, but I think that the `ResultIterator` also needs to be closed. On a similar topic the leak would happen if the Consumer does not consume, a stray `Handle` and `ResultIterator` will be left unclosed and it will cause the leak. Seems to me like we have something similar to session in view pattern that was deemed an anti-pattern in my Hibernate experience.

**Comment by zregvart** [comment]
Also @chirino could you take a look at #426, especially https://github.com/syndesisio/syndesis-rest/pull/426/files#diff-0a1e14613fa543c48ed87cf25e8808fb thanks 👍

**Comment by chirino** [comment]
I'll look into making sure we close those iterators.

**Comment by zregvart** [comment]
I think this was done.
