### ISSUE TITLE
Finishing OAuth credential flow on a wrong URL

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#431]
After resource provider callback client is redirected to URL that's relative to API base path (`/api/v1`) not UI. It is expected if given for acquisition `{"returlUrl": "/ui"}` the client should be redirected to `/ui` not `/api/v1/ui`.

**Comment by jimmidyson** [comment]
@zregvart Can you make sure you reference closed issues in the PR description with `fixes #number` please? Then they will get auto closed. We could add that to a PR lint check too possibly.

**Comment by zregvart** [comment]
> @zregvart Can you make sure you reference closed issues in the PR description with fixes #number please? Then they will get auto closed. We could add that to a PR lint check too possibly.

are we doing this in the commit message also?

**Comment by jimmidyson** [comment]
Yes as per conventional changelog guidelines.
