### ISSUE TITLE
CredentialProvider should define an id() method used to correlate the providers to connector ids.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-rest#438]
Right now CredentialProvider's are added to a registery by Spring's  provider id which may or may not match the connector id's defined by syndesis.  We should add an id() which we can control and make sure it matches our connector's id.

**Comment by chirino** [comment]
BTW.. our current strategy statically binds us to known connector ids.  Would we ever want to support doing oauth against a connector add at runtime (when we start allowing that sort of thing).

**Comment by zregvart** [comment]
This was done with #457
