### ISSUE TITLE
Exception handler missing or not working

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#454]
See https://github.com/syndesisio/syndesis-ui/issues/630 or #451 for where an internal error (500) is thrown and not the appropriate HTTP code.

**Comment by zregvart** [comment]
I've fiddled with exception handling in #441 could that be the cause?

**Comment by jimmidyson** [comment]
Possibly, but I doubt it if as @rhuss says it should be a 404, which I'd expect to be returned directly . We should definitely add some tests for this and document properly what status codes the REST API should generally provide.
