### ISSUE TITLE
Provide examples in UI - Domain document

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#458]
Tracking from review:

https://github.com/syndesisio/syndesis-rest/pull/434#pullrequestreview-51732543

**Comment by kahboom** [comment]
@zregvart - What is this for? Could you elaborate a bit more? Sorry, I'm a bit slow. :)

**Comment by zregvart** [comment]
Had to jog my memory also. We have a [document](https://github.com/syndesisio/syndesis-rest/blob/master/docs/design/ui-domain-object-map.adoc) detailing our domain model, would be awesome if that document, along with the terms and the description, also had concrete examples to make it even more easy to understand.
