### ISSUE TITLE
Update project generator to use properties defined for connectors via the global settings page

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-rest#468]

**Comment by zregvart** [comment]
I think it's `io.syndesis.credential.Applicator`s job to update anything relating to credentials to the Connection/Connector model. We use it now for `Connection`s perhaps it would make sense to use it for `Connector`s also.

**Comment by chirino** [comment]
Your right.  I guess we just need to also re-apply all the Applicators on a global settings change.

**Comment by chirino** [comment]
Looks like this should already be happening as @zregvart said via the Applicators.  Only edge case that's not flushed out is if a user wants to change and client id and secret in the global settings page.  He would need to manually re-setup the oauth connections.
