### ISSUE TITLE
Document API Endpoint Testing for Staging

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-rest#472]
I already forgot.. I think I used to use the Restlet client or curl and:

1. Set the host name (for Restlet).
2. Point to/upload the Swagger JSON (for Restlet).
3. Steal the `authenticationToken` from the UI, or pass in credentials manually to a login-type endpoint to get one the "right way", OR passing credentials/key file in each request URL (perhaps less secure and may not even work).

I'll test it shortly to see if I can still do this without issues, but if it is it would be nice to have this documented. I wouldn't mind doing this if I get it working again--any pointers to making this simpler are appreciated.

**Comment by KurtStam** [comment]
@jimmidyson we expire the tokens really fast, which makes it really hard to use the rest endpoint for testing. Can we enable password login on the rest api in addition to tokens? I think this would really help @kahboom.
