### ISSUE TITLE
New URL Structure for Fetching Filter Options Returns 500

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-rest#473]
As stated in [this](https://github.com/syndesisio/syndesis-ui/pull/671) PR--when loading the filter options, the URL structure was not correct as we had changed it to allow for passing in `connectorId` (`connectionId` in our case, I believe) & `actionId`, for which an issue had been opened up in the UI repo [here](https://github.com/syndesisio/syndesis-ui/issues/630). My PR for the fix was merged, but I still get a 500 when trying to POST any integration that contains a Basic Filter step. I've not tested the API appropriately, but will do so shortly.

Blocks this issue: https://github.com/syndesisio/syndesis-ui/issues/637

**Comment by gashcrumb** [comment]
@rhuss fixed this, should be all set
