### ISSUE TITLE
Better error message for connection validation

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#474]
The error message shown for a failing connection validation is a generic 'internal server' error. This happened to work for summit (i.e. to show a granular message, also pointing out what was missing).

While looking at the API one should also check, whether how it can be made more friendly to consume by the UI. Currently, the calls are given through 1:1 from the verifier to the UI, but requires some gymnastics within the UI to properly prepare the view.

**Comment by KurtStam** [comment]
@rhuss I think this can be closed now that we have https://github.com/syndesisio/syndesis-rest/pull/709

**Comment by rhuss** [comment]
Yes, but still I believe that the response from the verifier should be adapted for better consumption on the client side. But I'm going to open a new issue for this.
