### ISSUE TITLE
Build API endpoint to validate a connection name

### ISSUE THREAD

**Issue by akieling** [syndesisio/syndesis-rest#475]
Connection names are supposed to be unique and syndesis-ui needs to validate a connection name isn't already taken. It needs a way to get a connection by name or a confirmation that a connection already exists with that name.
[syndesis-ui #594](https://github.com/syndesisio/syndesis-ui/issues/594) depends on this issue.

**Comment by zregvart** [comment]
Linking to PR https://github.com/syndesisio/syndesis-rest/pull/499

**Comment by zregvart** [comment]
Fixed in #499
