### ISSUE TITLE
Provide better values for description, icon & label of AcquisitionMethod

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#478]
Currently those properties simply hold the name of the connector/provider id, they should be more descriptive and something that the UI can use.
- icon - should be per provider the icon that's usually used next or on the button for initiating OAuth flow
- label - the text for the button
- description - tooltip or text next to the button

**Comment by KurtStam** [comment]
@so are you talking about the data in the demo-data.json?

**Comment by zregvart** [comment]
@KurtStam this is about Credential endpoint at https://github.com/syndesisio/syndesis-rest/blob/311391fe0c1366103321569604ad78fbf0045266/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorCredentialHandler.java#L82 that stems from the fact that those are all fixed to `providerId` (here https://github.com/syndesisio/syndesis-rest/blob/311391fe0c1366103321569604ad78fbf0045266/credential/src/main/java/io/syndesis/credential/BaseCredentialProvider.java#L44-L54). Not sure if the UI relies on those, possibly not as they are so terse.
