### ISSUE TITLE
Separate the demo data out of deployment.json 

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-rest#482]
Right now deployment.json holds DB initialization data for connectors which we will need for normal customer deployments and some demo data used to define connections and sample integrations.  This demo data should be moved to a separate file and only be imported if the environment is configured to request the import of that demo data.

**Comment by jimmidyson** [comment]
Re naming advice, definitely prefer demo-data.json. What I'd like to see I think is a way to reference any external file to load on startup, so the name of this file is a bit immaterial I guess.
