### ISSUE TITLE
Identifier needed for connections that have been configured using an OAuth flow

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#513]
As far as as I know there's no difference between a connection that was created by filling in the form in the create connection wizard vs. going through an OAuth flow.  For the 'edit' screen to display the right interface we need an attribute on the connection that the UI can use.

**Comment by zregvart** [comment]
@gashcrumb something like a boolean named `derived`, would that do?

**Comment by gashcrumb** [comment]
Yep, that'd work I think!
