### ISSUE TITLE
Is there a cookie or session value that the rest API returns after an OAuth flow

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#514]
When the user is redirected back to the UI there's no way currently (that I know of) that we can tell what state the OAuth flow is in, is it completed, successful, failed, etc.  The UI would need some way of figuring this out, maybe a value in the cookie that reflects the state of the oauth flow, or an API to verify the oauth state for the selected connector ID?  That way we can either just forward the user on to the next step or have whatever feedback mechanism is in the design (can't recall off the top of my head) working to inform the user.

**Comment by zregvart** [comment]
I was thinking on extending the credentials design proposal, so we add parameters to the `returnUrl`, so in all cases the user would end up at the `returnUrl` but in error cases a parameters (probably flag or error code and a message) would be added as either query parameters or in the hash. Would that make sense?

see #464

**Comment by gashcrumb** [comment]
Yeah, there's probably not too many different kinds of errors, maybe a status flag and an error code; the UI could maintain an index locally that maps an error code to a message that the user would see.

**Comment by gashcrumb** [comment]
And the document hash is probably the right place for it, I actually need to change my redirect URL and code to use the document hash as well.
