### ISSUE TITLE
bug(rule-filter): Paths contains wrong prefix

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#517]
The rest endpoint which returns the possible options for a filter rule (wrt to the body) contains e.g. for twitter a "Status." prefix before the property (e.g. `Status.text`). Actually, this gets translated 1:1 to the generated simple expression. But instead of `Status.text` it must be `body.text`.

There can be two possible solutions:

* Either already use `body.text` for the auto suggestions in the filter rules (instead of `Status.text`)
* Translate automatically `<prefix>.<prop>` to `body.<prop>` when generating the simple expression. However, this becomes difficult if e.g. already well-known [simple](http://camel.apache.org/simple.html) prefixes like `in`, `headers`, `properties`, ... are used. 

Another, but a bit more involved solution would be, that in the options endpoint not only a single values path is returned but an object with two values: The one to display and autocomplete on (`Status.text`) and the one to be sent when the step is saved (`in.body.text` or `body.text`). @gashcrumb would this be too complicated to implement in the UI ? The drawback is that they would need to be translated back when editing the rule. hmmm.

So I tend to use the plain simple text (`body.user.screenName`) or even only without prefix at all `user.screenName` for the UI and then add the proper prefix when generating the rule.

E.g. a step would then have the following `configuredProperties`

```json
...
configuredProperties:
  predicated: "AND"
  pathPrefix: "Status"
  rules:
  - path: "user.screenName"
  - op: "equals"
  - value: "ro14nd"
```

This would be the most user-friendly variant (as you don't have to enter the common prefix "Status" at all). However, this would also close the door for 'advanced' expressions like filtering on the header or properties in this basic filter (one would need to use the advanced filter then). But considering we are targeting the citizen user here this might be not too much of a restriction (and even helps to keep it more simple) ?

**Comment by gashcrumb** [comment]
Isn't `Status` the java type of the body?  Couldn't this then be used to figure out the prefix?
