### ISSUE TITLE
bug(github): Email and User of git commits are not properly set

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#518]
The generated and checked in files in GitHub do not contain a proper user or email name (but only a single '?') mark. Wonder whether this should be a configuration option, too ?

**Comment by jimmidyson** [comment]
We should be sure to retrieve the name and email address when we get the username as part of the git flow. I'm out today but can look tomorrow, unless someone (@KurtStam?) gets there first.
