### ISSUE TITLE
Update atlasmapping in demo-data.json

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#521]
Currently the mapping in demo-data.json refers to the old format of the atlas data mapping. this nees to be upgraded to actual schema and class names as used in the newest version of atlasmap.

**Comment by KurtStam** [comment]
@rhuss can you specify what it is you want to see changed?

**Comment by igarashitm** [comment]
This one maybe? mapping definition
https://github.com/syndesisio/syndesis-rest/blob/master/dao/src/main/resources/io/syndesis/dao/demo-data.json#L130

Yeah it actually contains com.mediadriver.atlas.v2.AtlasMapping which is really old. And the target salesforce object is java type, not json like today.

**Comment by rhuss** [comment]
afair it was because of just old classes which do not exist anymore. I think we should rethink demo-data.json anyway. It should either contains something functional (not only UI candy) or we should remove it.

As it is not installed by default anyway these days, its not so critical anymore.
