### ISSUE TITLE
Rename verifier - Maven module - to a more generic name

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#524]
We need verifier and metadata in the same micro-service, we should rename `syndesis-verifier` to a more general purpose name.

**Comment by rhuss** [comment]
agreed. btw, the verifier lives in https://github.com/syndesisio/syndesis-verifier, so maybe that's the proper place for an issue ? ;-)

**Comment by zregvart** [comment]
I would keep this open as both the repository and the Maven module (`verifier`) in `syndesis-rest` could be renamed.

(another point for the monorepo, btw)

**Comment by KurtStam** [comment]
So let's come up with some names: connectors-designtime

**Comment by zregvart** [comment]
Linking to https://github.com/syndesisio/syndesis-verifier/issues/16

adding `connector-support` to the mix

**Comment by rhuss** [comment]
Let's continue in https://github.com/syndesisio/syndesis-verifier/issues/16 ....
