### ISSUE TITLE
Can't remove oauth client credentials anymore

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#536]
On staging clicking 'Remove' no longer clears stored client credentials, instead you get this error popup:

`Failed to delete settings: Response with status: 500 Internal Server Error for URL: https://localhost:4200/api/v1/setup/oauth-apps/twitter`

This used to work, note to clear the credentials we're currently setting the ID and secret to empty strings, so I guess this is a side-effect of trimming incoming JSON messages.

@zregvart @jludvice FYI...

**Comment by zregvart** [comment]
With https://github.com/syndesisio/syndesis-rest/pull/527 the strings are trimmed and empty strings are converted to `null`, I guess we're trying to set a `null` value via Immutables. And that is a no-no.

**Comment by gashcrumb** [comment]
BTW we could do a DELETE but it does seem odd only because technically these oauth client parameters can't be deleted by the frontend, only cleared.

I would say be careful also in general converting empty strings to null values, what if a user actually wants an empty string (or a space) in a field for some weird reason...

**Comment by jludvice** [comment]
relates to syndesisio/syndesis-ui#882
