### ISSUE TITLE
Clicking cancel in twitter during oauth flow causes a redirect back to the root of the syndesis app

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#557]
Also I noticed the connectorId is 'null' instead, so unfortunately we lose all context of what the user was doing before starting the oauth flow.

**Comment by gashcrumb** [comment]
@zregvart FYI doesn't block getting the UI to at least look at the status object though, so...

**Comment by zregvart** [comment]
Yeah, I left this for #464 but at least is not #509. In some cases client side state cannot be restored, I'm not sure why it wouldn't be in this particular one, but without state the backend doesn't know what connectorId was the dance for.
