### ISSUE TITLE
Add configuration for the maximum number of integration to run

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#559]
For preview release, it's important to be able to set a hard limit on the number of integrations which can be created. 

This should be an installation-global parameter, set via the template.

However, for this to work properly we must be able to delete integration, not only in the DB but also OpenShift wise.

**Comment by rhuss** [comment]
See #560 for deleting integration objects.

**Comment by jimmidyson** [comment]
Closed by #608
