### ISSUE TITLE
Deleting an integration needs to delete the runtime objects

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#560]
When an integration is deleted, then all OpenShift runtime objects (build, deployment, secrets, ...) should be deleted, too.

This seems to be not the case currently.

**Comment by iocanel** [comment]
This has already been implemented as part of https://github.com/syndesisio/syndesis-rest/commit/c711b763d6d2757ea0f8a4a38e40a3861fe0e812#diff-058df094d1cb29689564ded64cd5cb6a
