### ISSUE TITLE
Need a startTime field in the integration revision list

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#600]
@gashcrumb commented on [Thu Sep 14 2017](https://github.com/syndesisio/syndesis-ui/issues/957)

@iocanel FYI

Not sure if 'startTime' makes sense honestly, maybe the commit/save date?  I can adjust the table header accordingly.

**Comment by gashcrumb** [comment]
If the revision object in a row happens to have a `startTime` attribute the UI will show that instead of fake data.  Ideally the date format should follow https://www.w3schools.com/js/js_date_formats.asp so I can pass it along to `Date.parse()`

**Comment by rhuss** [comment]
Maybe the time of the last message fetched ? Just as an indication that the integration is still running ? (e.g. when this time is too long in the past then this might be suspicious)

**Comment by iocanel** [comment]
I am not sure I get what the problem is or what is to be done?

Are we displaying the wrong date? not a date at all? Can u elaborate?

**Comment by gashcrumb** [comment]
Currently there's no field that I can use for the `startTime` column, the date shown there currently is fake data.  I guess though if it's supposed to indicate the date when that revision was actually started then it can be blank.  

Seems weird to have in the history table honestly, I'd think 'Start Time' would be more useful only for the current running integration, whereas for integration history you'd want to know the date/time that revision was committed.

**Comment by rhuss** [comment]
Agree, it makes more sense to have that in a general 'monitoring' page / dashboard along maybe we other kind of analytics ?

tbh, for TP1 I don't think we get any of these extra fields in the details page.

**Comment by gashcrumb** [comment]
I can hide any of those columns easily enough if needed
