### ISSUE TITLE
Need a runLength field in the integration revision list

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#601]
@gashcrumb commented on [Thu Sep 14 2017](https://github.com/syndesisio/syndesis-ui/issues/958)

@iocanel FYI

If we can get this data at least, I guess it should be the amount of time that particular version of the integration was running?

**Comment by gashcrumb** [comment]
Added some code to show a real value if the revision contains a `runLength` attribute.  Ideally this would be in seconds

**Comment by rhuss** [comment]
Actually, what should this mean ? Time of last exchange passing the route ? Average Time ? Longest time ? Again connected to https://github.com/syndesisio/syndesis-project/issues/42

@kcbabo Are there any other metrics we might make sense in this place ? E.g. number of errors, percentiles, ....

**Comment by iocanel** [comment]
Can we just derive the runLength from `createdDate`, `lastUpdateDate` and status?

**Comment by kcbabo** [comment]
We should consider this in the context of the larger metrics story and use stories for monitoring.  I do think uptime is an interesting metric to track.
