### ISSUE TITLE
Need a 'uses' field for integration revisions

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#602]
@gashcrumb commented on [Thu Sep 14 2017](https://github.com/syndesisio/syndesis-ui/issues/959)

@iocanel FYI

Or I guess the number of camel exchanges processed for that particular revision of the integration

**Comment by gashcrumb** [comment]
Added some code to show a real value if the revision contains a `uses` attribute.

**Comment by rhuss** [comment]
This also connected to https://github.com/syndesisio/syndesis-project/issues/42 where to fetch the health status of a running integration. The same way number of messages processed could be queried (not sure whether available out of the box)
