### ISSUE TITLE
Status/State fields in an integration revision need adjusting

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#603]
@gashcrumb commented on [Thu Sep 14 2017](https://github.com/syndesisio/syndesis-ui/issues/960)

@iocanel 

So for the status/state column the design kinda shows 2 things.  Status being whether or not that integration revision successfully processed messages and a runtime state, which should of course be only for the currently running revision.  Currently we have the desired and current status fields, previous revisions all seem to show 'pending' for both.

**Comment by rhuss** [comment]
Is 'Pending' still a fixed state (i.e. part of the state enum and possible value of 'currentState') ? 

I might not really up-to-date of the current plan, but according to the proposal the idea was that 'Pending' is a _derived state_, e.g. when the `currentState != desiredState` and never set explicitely.

**Comment by iocanel** [comment]
The integration object has been left untouched, and we just added `revisions` & `deployedRevisionId` so changes are forward compatible (to limit friction between rest & ui).

The integration revision state, use the new states as defined by the proposal, though for now they are just mapped to the integration state (as was at the time the revision was created).

I will have a look and see why previous revisions have issues.
