### ISSUE TITLE
Integration should probably have a 'version' attribute

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#604]
@gashcrumb commented on [Thu Sep 14 2017](https://github.com/syndesisio/syndesis-ui/issues/961)

So it's easy to correlate which version out of the revision list is running.

@iocanel FYI

**Comment by iocanel** [comment]
@gashcrumb: we have a field called `deployedRevisionId` that correlates with the version.

**Comment by gashcrumb** [comment]
Ah, and that'd only be available when you've actually deployed an integration, k...

**Comment by gashcrumb** [comment]
Added code to check for this field and display that revisions runtime state, think this should be all set then.

**Comment by gashcrumb** [comment]
I wonder though, should we consider having a `desiredRevisionId` attribute perhaps?  The `deployedRevisionId` field doesn't show up unless the integration has actually been deployed.

**Comment by rhuss** [comment]
Actually, any integration which has never been deployed (i.e. is in state draft) has no revision as it can still change freely. It's only after the first deployment when it's 'frozen' and gets a revision number assigned. So it seems to be leggit to have one revision with a revision id, the 'draft' revision where people are still working on it.

**Comment by iocanel** [comment]
Now, I am a little bit confused. Is it fine as is, or we need to change that?

**Comment by gashcrumb** [comment]
Yeah, @rhuss's explanation works for me, so @iocanel nothing to be done I think.
