### ISSUE TITLE
Integrations should always have at least 1 revision

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#605]
Even newly created integration should have 1 revision at least, currently when you create an integration it has no revisions.

**Comment by rhuss** [comment]
Actually according to the design proposal this works as planned. The idea is, that you only get a revision when you are deployed. So when an revision is in state draft (there must be only a single revision in state draft), then it has no number. This indicates that it can still be changed without history. Also the idea is as soon as a revision id is set, the revision becomes immutable.

Of course this might be discussable and might have drawbacks. but that was the original idea to distinguish different which revision can be changed (draft) and which are froznen, to ensure that a version doesn't change anymore.

**Comment by gashcrumb** [comment]
The trouble is when you've made your first save and go back to the detail page, the history table is totally empty.  I'd expect to see at least one entry in there, even if it's a draft.

**Comment by rhuss** [comment]
If one sees the history as a "history of published integrations" I think this is not so confusing anymore. Maybe one could ommit the table completely then and instead print sth like "No integration published" (which is also an important info).

**Comment by gashcrumb** [comment]
Agreed!  What property would be the definitive way of knowing the integration has been published, the `deployedRevisionId`?

**Comment by rhuss** [comment]
Think `deployedRevisionId` is a good start, although it could be that there is no currently deployed revision although there have been some deployments before. The definitive answer can probably be  only inferred by looking at the revisions of an integration. If there is on with an id, there's is a history.

But we might consider adding an additional property to the integration itself, indicating e.g. the number of deployed revisions or so.

@iocanel any idea here maybe ?

**Comment by iocanel** [comment]
The `deployedRevisionId` is expected to get vlaue of `1` when the first draft becomes activated and from that point on will always point to the `currently deployed revision`. When we assign value to `deployedRevisionId` we also add the revision inside the `revisions` list. 

Now, I am not sure I get what you mean by `published` revision. My understanding is that the user has pressed the "publish" button, but the revision has not been yet activated. If this is the case, the only way to know that is by checking the desiredStatus on the integration object. Note, that at this point no revision will be inserted in the `revisions` list (we could possibly change that).
