### ISSUE TITLE
event stream SSE connection closes after about a minute

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#619]
I raised this issue a few days ago -> https://github.com/syndesisio/syndesis-ui/issues/967

and am working on adding client-side code to handle reconnecting.  Couple questions though:

1)  What happens to stale/old reservations?  Am hoping when I get disconnected I can just claim a new reservation and reconnect
2)  Is there a gateway timeout kicking in that's closing the connection on us here that we could tweak?  The connection is dropped consistently.

**Comment by chirino** [comment]
1. You can just create a new reservation.  The only issue is that you will only get event from the point in time the reservation is claimed.  You might drop event between the disconnect and the claim getting established.

2. Yeah, might be.. might also be idle settings between the client and server not be exactly right.  Undertow did no let me configure those.  Need to recheck to see if a more recent version allows it.
