### ISSUE TITLE
Integration s2i build requires additional Maven repositories 

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-rest#623]
Since the switch to Camel version `2.20.0.fuse-000093`. We need to point s2i build to required EA (or TP) repos.

Cc @rhuss @zregvart

**Comment by aileenc** [comment]
Is this a duplicate of https://github.com/syndesisio/syndesis-rest/pull/625?

**Comment by dsimansk** [comment]
This was fixed via PR #625, closing it now.
