### ISSUE TITLE
can't edit oauth apps in syndesis settings page

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-rest#637]
![settings](https://user-images.githubusercontent.com/8707241/30799054-e46e139c-a1db-11e7-99f3-6921d8aa493c.png)

**Comment by zregvart** [comment]
This is due the `syndesis-db` volume (2GiB) being full, I've reset PostgreSQL transaction logs and vacuumed the database. We still have a huge number of rows (887402) out of which integration revisions for two integrations take up 434046 and 332934 rows. I've created #638 to fix that.

Now the `syndesis-db` has enough free space to run, and the settings pages are displayed.
