### ISSUE TITLE
Swagger.json link only shows one operation

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#646]
Noticed that the swagger link that points to swaggerui in the readme only shows the /setup path and no other operations but instead a little error box as it fails to validate:

```
{
  "messages": [
    "attribute info.title is missing"
  ],
  "schemaValidationMessages": [
    {
      "level": "error",
      "domain": "validation",
      "keyword": "required",
      "message": "object has missing required properties ([\"title\"])",
      "schema": {
        "loadingURI": "http://swagger.io/v2/schema.json#",
        "pointer": "/definitions/info"
      },
      "instance": {
        "pointer": "/info"
      }
    }
  ]
}
```

It'd be good if the whole swagger rendered properly -> https://online.swagger.io/validator/debug?url=https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/v1/swagger.json

**Comment by zregvart** [comment]
I wonder why is this still the case now that we've removed GitHub setup from the backend?

**Comment by KurtStam** [comment]
The title field was added in https://github.com/syndesisio/syndesis-rest/pull/731/commits/fb836a79353c3efbe6acaaf229dd8161d16a13f9, but a new issue popped up

Swagger schema validation failed. 
  Array items are not unique (indexes 0 and 1) at #/paths//connectors/{id}/actions/{id}/get/parameters

where we simply have to better name the id field parameters.
first id -> connectionId
second id -> actionId

**Comment by KurtStam** [comment]
@jimmidyson I tried overriding the second parameter with 'actionId' but that doesn't seem to be possible. I think we only have two options: 

- remove the swagger annotations on Getter
- stick with invalid swagger

Any thoughts?
