### ISSUE TITLE
Error 500 on /api/setup endpoint

### ISSUE THREAD

**Issue by akieling** [syndesisio/syndesis-rest#655]
**Current behavior**
Invoking /api/setup is throwing error with status code 500

**Expected behavior**
It should not throw any errors

**Steps to reproduce**
1. Download https://github.com/kahboom/syndesis-ui/tree/952-github-oauth
1. Start the app
1. Go to https://localhost:4200/setup
1. On step 2, enter client ID and client secret and press Connect GitHub button (this action sends a PUT to `/api/setup` as specified in https://github.com/syndesisio/syndesis-rest/pull/626)
1. Check the browser console and the syndesis-rest logs

**Logs**
`2017-09-29 18:30:52.542 ERROR [-,,,] 1 --- [  XNIO-3 task-6] io.undertow.request                      : UT005023: Exception handling request to /api/setup

java.lang.NullPointerException: null
at io.syndesis.runtime.SyndesisCorsConfiguration.lambda$corsFilter$0(SyndesisCorsConfiguration.java:46) ~[classes!/:0.1-SNAPSHOT]
at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:87) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]`

**Comment by rhuss** [comment]
@akieling I just pushed a fix for this very NPE to GitHub, the image should be build soon after and staging should be updated then in around 30mins.

Please let me know whether this helps. I tried to test the setup locally but failed. Will check tomorrow again.

**Comment by akieling** [comment]
@rhuss that seems to fix it but now I'm getting another error. Maybe an OpenShift route configuration?
```
Error: Response with status: 404 Not Found for URL: https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/setup
```

**Comment by rhuss** [comment]
Yes, it seems that this route definition is missing for the setup application. @jimmidyson I can't see that in the OpenShift templates, too. 

Let me try to guess it and add it manually to staging.

**Comment by jimmidyson** [comment]
Route has been corrected in openshift templates in syndesisio/syndesis-openshift-templates#102 and applied to staging (thanks @rhuss!).

**Comment by rhuss** [comment]
@akieling I just recreated staging with the latest set of templates (except that I removed the imagestreams from the init-container as we are running on 3.5 here). `api/setup` triggers now the proper end point, but I get a `410 Gone` as the application seems to be already setup. Any quick way to set it into a state for setup to work ?

**Comment by jimmidyson** [comment]
try https://raw.githubusercontent.com/syndesisio/syndesis-rest/master/setup/reset-github-provider.sh

**Comment by zregvart** [comment]
Given that we've removed GitHub support is this still relevant?
