### ISSUE TITLE
Non-unique deleted integration name

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#663]
When the user deletes an integration at the end the status is changed to `Deleted` and the integration rows are still present in the database.
We should either delete those rows or ignore integrations with `Deleted` status when considering integration name uniqueness. Possibly both.

**Comment by akieling** [comment]
If the status is changed to `Deleted`, then it seems that the plan is to keep these integrations in the database, isn't it? I think the validation just needs to ignore deleted integrations.

**Comment by zregvart** [comment]
I'll close this in favour of https://github.com/syndesisio/syndesis-rest/issues/687
