### ISSUE TITLE
Remove checkstyle rule about JLS ordering

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#681]
For my life, I can't memorize the order. I tried it since ten years. It has cost me are more than 2 months of lifetime, because of failed builds. This is a stupid rule. I hate it. with a passion.

```
 'private' modifier out of order with the JLS suggestions.
```

die. die. die.

**Comment by zregvart** [comment]
Perhaps [code arrangement rules](https://www.jetbrains.com/help/idea/rearranging-code-using-arrangement-rules.html) could help.

Also at some point I would like to bring up a pre|post-commit formatter hook discussion back.

I don't mind code having spaces or tabs, two or four indentation, curly brackets at the end or on the new line. What I care is that all code looks the same. I usually force everyone to use the same formatter and formatting rules were in SCM. If you did not format the code by those rules your code would be reformatted by someone else's format-on-save action.

This is good practice™️ as eliminates unnecessary issues when merging. Code needs to be formatted with the same formatter, methods need to be sorted.

If the editor automatically reformats and places the modifiers in the correct order, for whatever definition of correct order, this becomes a non-issue.

**Comment by rhuss** [comment]
agreed, got to love gofmt. I even don't care if a system reformats stuff, consistency is king (but even then, I'm learning to look over that). If it does not slow down things, I'm totally for it.

BTW, I also have the feeling that many of the nitpicky things that PMD, Checkstyle, Codacy and friends are reporting could be fixed automatically. No need to waste 20 minutes lifetime ...

**Comment by rhuss** [comment]
> Perhaps code arrangement rules could help.

yeah, but I never to a reformat of shared code (only then arrangement rules apply). For reasons. If there were fixed formatting rules, then, of course, this is no problem. But otherwise, and for PR reviews sake, I'm staying away from this.
