### ISSUE TITLE
Limit the execution time of integration tests

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#684]
We changed failsafe timeout to 0 in c3e55bfce65ada4de08a7b7f14e04ec50dceb28b, we should bring it back when we measure and determine how much time do we want to spend in integration tests.

**Comment by rhuss** [comment]
Yes, we should do this when we removed keycloak as I suspect that this has quite some impact here.

**Comment by zregvart** [comment]
I don't think Keycloak is counted in that timeout. I think only the test execution time in the forked JVM is counted...

**Comment by KurtStam** [comment]
The integration tests were addressed in:
https://github.com/syndesisio/syndesis-rest/pull/654.
