### ISSUE TITLE
Do we still need the `setup` module?

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#708]
This was needed for GitHub setup but that's no longer in play, we should remove it.

**Comment by gashcrumb** [comment]
Does it also contain the OAuth app management stuff too?  As I remember it lives at `v1/setup/oauth` or thereabouts...

**Comment by zregvart** [comment]
@gashcrumb I don't think so, that's a REST handler here: https://github.com/syndesisio/syndesis-rest/tree/master/rest/src/main/java/io/syndesis/rest/v1/handler/setup

**Comment by gashcrumb** [comment]
ok cool

**Comment by zregvart** [comment]
Would also fix #646 I think

**Comment by jimmidyson** [comment]
this is removed in the keycloak removal pr btw

**Comment by zregvart** [comment]
@jimmidyson would you mind if I remove it in another PR, would like to have it removed as soon as possible and seems straightforward?

**Comment by jimmidyson** [comment]
of course I don't mind, it was just a heads up
