### ISSUE TITLE
Make DeploymentDescriptorTest an integration test

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#715]
DeploymentDescriptorTest should be run by failsafe as it is not a unit test, will help with test timeouts we're experiencing in CI.

**Comment by KurtStam** [comment]
+1 can we move it to the runtime module?

**Comment by zregvart** [comment]
I would not as it reads `deployment.json` from the dao project, so if you make a change there a test there should fail IMHO.

**Comment by KurtStam** [comment]
y I though it was deploying something, but it's not.

**Comment by zregvart** [comment]
Yeah I added that test to test that we don't stray too far from the Camel connector JSONs in our `deployment.json` and that we can catch any missed refactorings (like we had with changing names/schemes of the twitter and sql stored connectors).
