### ISSUE TITLE
Link up credentials with the dynamicaly generated API Connector

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#724]
When we create an API Connector for syndesisio/syndesis-project#119 if that new API connector is configured to use OAuth then it needs to follow the same flow as Twitter or Salesforce do using the Credentials API. So it needs to be registered with appropriate type (OAuth1, OAuth1A, OAuth2) and other settings needed for the OAuth to work.

**Comment by KurtStam** [comment]
@zregvart this needs a description
