### ISSUE TITLE
Salesforce "Identifier field" is always "Contact ID"

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#733]
Regardless what I chose, its always "Contact ID" which is saved.

This leads to errors in the runtime whose error message is strange, too (saying sth like sObjectId not provided, instead of being wrong), but I have to lookup this again.

**Comment by rhuss** [comment]
![image](https://user-images.githubusercontent.com/99080/31763970-2ec3285a-b4c0-11e7-982b-db7ad5b328c7.png)

Minor thing, there's not "arrow down" element to select the other elements. Dealing with the field is a bit counter intuitive ....

**Comment by rhuss** [comment]
That's the error I get in the runtime:

```

Message History
--
  | ---------------------------------------------------------------------------------------------------------------------------------------
  | RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
  | [flow1             ] [flow1             ] [twitter-mention-connector-component://MENTIONS?delay=30000&sinceId=1          ] [         5]
  | [flow1             ] [to1               ] [atlas:mapping-step-2.json                                                     ] [         5]
  | [flow1             ] [to2               ] [salesforce-upsert-sobject?sObjectIdName=Id&sObjectName=Contact                ] [         0]
  |  
  | Stacktrace
  | ---------------------------------------------------------------------------------------------------------------------------------------
  | org.apache.camel.component.salesforce.api.SalesforceException: Missing option sObjectIdName
  | at io.syndesis.connector.salesforce.SalesforceUpsertSObjectComponent.lambda$new$0(SalesforceUpsertSObjectComponent.java:56)
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
  | at org.apache.camel.component.connector.ConnectorProducer.process(ConnectorProducer.java:45)
  | at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
```

**Comment by rhuss** [comment]
but sObjectIdName is given here ....

**Comment by zregvart** [comment]
> Minor thing, there's not "arrow down" element to select the other elements. Dealing with the field is a bit counter intuitive ....

This is the default behaviour of [Patternfly Bootstrap Combobox](https://www.patternfly.org/pattern-library/widgets/#bootstrap-combobox), you need to click on 'X' on the far right to get other options.

**Comment by zregvart** [comment]
> Regardless what I chose, its always "Contact ID" which is saved.

@rhuss do you mean regardless of what you choose on the previous screen (selecting the Salesforce object) or if you end up choosing another unique field on the second screen no matter what you choose `Contact ID` gets saved?

**Comment by zregvart** [comment]
> That's the error I get in the runtime:

That error is caused by not providing a value for the unique field (mapping issue)? Using `ID` as external identifier doesn't make much sense to me...

**Comment by rhuss** [comment]
> @rhuss do you mean regardless of what you choose on the previous screen (selecting the Salesforce object) or if you end up choosing another unique field on the second screen no matter what you choose Contact ID gets saved?

Exactly.

**Comment by rhuss** [comment]
I've chosen"Contact". Then I get "Contact Id" prefilled, but change this to "TwitterScreenName". Then "Save as Draft", "Edit" and its back to "Contact Id".

**Comment by rhuss** [comment]
... prefilled for the "Identifier" field ...

**Comment by gashcrumb** [comment]
Yeah, so what's happening is the combobox is a jquery control that doesn't trigger angular's change detection when you change the value, so the page controller doesn't get the updated value.  Looking into getting that sorted.

**Comment by rhuss** [comment]
The same btw happens for me also for the first form where you select "Contact".
