### ISSUE TITLE
Tech extension : add filestore with initial db backend

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis-rest#735]
Tech extension will be uploaded as binary blob (jar) we need to store on back-end side thus we need a filestore with pluggable storage. Initial storage implementation should be database based.

**Comment by KurtStam** [comment]
@lburgazzoli can you add a description, and maybe add a link to the design for tech extension so we understand how this fits in?

**Comment by lburgazzoli** [comment]
@KurtStam added a little description.
