### ISSUE TITLE
RC gets not removed after a redeployment

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#739]
When an integration changes and gets redeployed, a new ReplicationController is created, _but the old RC is not deleted_. Not exactly sure, whether this should be done manually or is a task for OpenShift.

Nevertheless, this leads that we run out of RC object count quota quite quickly on our production cluster (quota is 20 RC over all apps).

@jimmidyson any idea how to tune this openshift-wise ?

**Comment by jimmidyson** [comment]
I think we can tune the `revisionHistoryLimit` on the DC definition to remove old RCs, but that would mean no rollback - I don't think we're using that anyway are we? I'll send in a PR for discussion.

**Comment by rhuss** [comment]
No, a 'rollback' is always a new deployment. Actually we do not keep to _any_ revison as we can recreate everything from our history. And we are using a recreate policy and only one pod, we can get rid of it completely.
