### ISSUE TITLE
NPE with Twitter to Saleforce integration

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis-rest#740]
Hi, I'm currently hitting a NPE following the tutorial:

<details>
  <summary>Click to expand</summary>
<pre>
15:30:07.475 [HttpClient@1885991030-21] ERROR o.a.c.processor.DefaultErrorHandler - Failed delivery for (MessageId: ID-twitter-to-salesforce-sample-integration-12-7kzwd-1508426997277-0-42 on ExchangeId: ID-twitter-to-salesforce-sample-integration-12-7kzwd-1508426997277-0-39). Exhausted after delivery attempt: 1 caught: java.lang.NullPointerException

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[flow1             ] [flow1             ] [twitter-mention-connector-component://MENTIONS?delay=30000&sinceId=1          ] [       182]
[flow1             ] [filter1           ] [filter[{io.syndesis.integration.runtime.util.JsonSimplePredicate@2251b3bc}]   ] [       182]
[flow1             ] [to1               ] [atlas:mapping-step-3.json                                                     ] [         2]
[flow1             ] [to2               ] [salesforce-create-sobject?sObjectName=Contact                                 ] [       179]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.lang.NullPointerException: null
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:879)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
	at io.syndesis.connector.salesforce.SalesforceCreateSObjectComponent.lambda$new$0(SalesforceCreateSObjectComponent.java:40)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
...
</pre>
</details>

I suspect that I have either made an error at mapping level, despite I have checked multiple times.

<details>
  <summary>Click to expand</summary>
<pre>
bash-4.2$ unzip -c project-0.1-SNAPSHOT.jar BOOT-INF/classes/syndesis.yml                                                                                                                                                                                                      
Archive:  project-0.1-SNAPSHOT.jar
  inflating: BOOT-INF/classes/syndesis.yml  
---
flows:
- steps:
  - kind: endpoint
    uri: twitter-mention-connector:MENTIONS
  - kind: filter
    expression: ${body.text} contains '#signorefammistrumentodipace'
    steps:
    - kind: endpoint
      uri: atlas:mapping-step-3.json
    - kind: endpoint
      uri: salesforce-create-sobject?sObjectName=Contact
</pre>
</details>

<details>
  <summary>Click to expand</summary>
<pre>
bash-4.2$ unzip -q -c project-0.1-SNAPSHOT.jar BOOT-INF/classes/mapping-step-3.json | python -m json.tool
{
    "AtlasMapping": {
        "dataSource": [
            {
                "dataSourceType": "SOURCE",
                "id": "twitter4j.Status",
                "jsonType": "io.atlasmap.v2.DataSource",
                "uri": "atlas:java?className=twitter4j.Status"
            },
            {
                "dataSourceType": "TARGET",
                "id": "Contact",
                "jsonType": "io.atlasmap.json.v2.JsonDataSource",
                "template": null,
                "uri": "atlas:json:Contact"
            }
        ],
        "jsonType": "io.atlasmap.v2.AtlasMapping",
        "lookupTables": {
            "lookupTable": []
        },
        "mappings": {
            "mapping": [
                {
                    "inputField": [
                        {
                            "docId": "twitter4j.Status",
                            "fieldType": "STRING",
                            "jsonType": "io.atlasmap.java.v2.JavaField",
                            "name": "name",
                            "path": "/user/name"
                        }
                    ],
                    "jsonType": "io.atlasmap.v2.Mapping",
                    "mappingType": "SEPARATE",
                    "outputField": [
                        {
                            "docId": "Contact",
                            "fieldType": "STRING",
                            "index": 0,
                            "jsonType": "io.atlasmap.json.v2.JsonComplexType",
                            "name": "FirstName",
                            "path": "/FirstName",
                            "userCreated": false
                        },
                        {
                            "docId": "Contact",
                            "fieldType": "STRING",
                            "index": 1,
                            "jsonType": "io.atlasmap.json.v2.JsonComplexType",
                            "name": "LastName",
                            "path": "/LastName",
                            "userCreated": false
                        }
                    ],
                    "strategy": "Space"
                },
                {
                    "inputField": [
                        {
                            "docId": "twitter4j.Status",
                            "fieldType": "STRING",
                            "jsonType": "io.atlasmap.java.v2.JavaField",
                            "name": "screenName",
                            "path": "/user/screenName"
                        }
                    ],
                    "jsonType": "io.atlasmap.v2.Mapping",
                    "mappingType": "MAP",
                    "outputField": [
                        {
                            "docId": "Contact",
                            "fieldType": "STRING",
                            "jsonType": "io.atlasmap.json.v2.JsonComplexType",
                            "name": "Title",
                            "path": "/Title",
                            "userCreated": false
                        }
                    ]
                },
                {
                    "inputField": [
                        {
                            "docId": "twitter4j.Status",
                            "fieldType": "STRING",
                            "jsonType": "io.atlasmap.java.v2.JavaField",
                            "name": "text",
                            "path": "/text"
                        }
                    ],
                    "jsonType": "io.atlasmap.v2.Mapping",
                    "mappingType": "MAP",
                    "outputField": [
                        {
                            "docId": "Contact",
                            "fieldType": "STRING",
                            "jsonType": "io.atlasmap.json.v2.JsonComplexType",
                            "name": "Description",
                            "path": "/Description",
                            "userCreated": false
                        }
                    ]
                }
            ]
        },
        "name": "UI.278186",
        "properties": {
            "property": []
        }
    }
}

</pre>
</details>

![screenshot from 2017-10-20 10-07-34](https://user-images.githubusercontent.com/1520602/31811094-91f38028-b57e-11e7-8232-e94380adcdbd.png)

**Comment by zregvart** [comment]
I think this could be due to Salesforce returning no body, we had a similar issue with [upsert connector](https://github.com/syndesisio/connectors/commit/2cefd38cb41235fdb61ea6dd224a68fc57154cad).
I could also be masking any exceptions that Salesforce component might be raising.

**Comment by paoloantinori** [comment]
Thanks @zregvart for your comments. Without a full understanding of the whole flow, I'm struggling to interpret issues as my own mistakes, runtime hiccups, evolving APIs or whatever other reason to consider when I face a problem.
