### ISSUE TITLE
model: make Actions generics to handle tech extensions

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis-rest#742]
In the current model a Syndesis Action is tightly couple to a Camel Connector so it carries the following non optional methods:

```java
public interface Action extends ...  {
    ...
    String getConnectorId();
    String getCamelConnectorGAV();
    String getCamelConnectorPrefix();
}
```

To reuse the same concepts we should break/relax that link:

1. Add a generic "Attributes" to hold context specific information

    ```java
    public interface Action extends ...  {
        ...
        Map<String, String> getAttributes();
    }
    ```

    So a connector related action could host the connector coordinates as attributes. This of course is a less strict definition.

2. Add dedicated sections for Connectors and Extensions:

     ```java
    public interface Action extends ...  {
        ...
        Optional<ConnectorDescriptor> getConnectorDescriptor();
        Optional<ExtensionDescriptor> getExtensionDescriptor();
    }
    ```

Leveraging actions would make us re-use dynamic actions to list steps provided by tech extension.

@rhuss @zregvart @KurtStam any better way to do so ?

**Comment by zregvart** [comment]
Perhaps something like:

```java
public interface Action<D extends Descriptor> extends ...  {
   ...
   Optional<D> getDescriptor();
}
```

I'm not 100% sure that the descriptor property is optional, perhaps I'm not seeing a use case when it would be omitted.

Also tagging @jimmidyson and @iocanel (or @syndesisio/backend)

**Comment by lburgazzoli** [comment]
I guess then we need to add some more info to the json for Jackson to properly deserialize, isn't it ?

**Comment by lburgazzoli** [comment]
@syndesisio/backend does the comment above make sense ?

**Comment by jimmidyson** [comment]
Yes that looks OK to me.

**Comment by lburgazzoli** [comment]
@gashcrumb if we do that, is there anything that would breaks at ui ? :)

**Comment by gashcrumb** [comment]
Moving the `connectorId` would be a breaking change but now is the time to do it.  I like the idea of putting this kind of metadata into a descriptor property with a kind to figure out what the action is.

Crazy thought, does the name `Action` make sense still then?  Maybe something to consider renaming in a future iteration.

**Comment by lburgazzoli** [comment]
@syndesisio/backend 

I see that an action has `ActionDefinition getDefinition()` would it be ok if I rename it to `getDescriptor` to match the proposed design ?

**Comment by rhuss** [comment]
@lburgazzoli renaming is fine for me.
