### ISSUE TITLE
Add new 'pattern' field to the connector 

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis-rest#751]
The Camel connector has a 'pattern' field we should capture. This field can contain 'To' and 'From' (and maybe 'anywhere' - have to look that up, if so then we'd need to add it to Action as well). And the UI should filter by it when displaying possible connectors/connections/actions. A 'Start' should only from 'From' patterns.

**Comment by gashcrumb** [comment]
So the semantics for this require some thought:

* `From` shouldn't be in the last step
* `To` shouldn't be in the first step
* `Anywhere` obviously can always be used if we have this possibility too

Question though:

* Can a `From` be used in a middle step, or is it only for the first step?
* Likewise for a `To`, can it show up in the middle of an integration?

I think the answer for either above is probably yes, these could show up in the middle of an integration, but I could be wrong there :-)

**Comment by KurtStam** [comment]
Pretty sure the `From` can be in the first step only. `to` can occur in multiple times and can be in the middle. https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/6.3/html/apache_camel_development_guide/basicprinciples

**Comment by rhuss** [comment]
@KurtStam is you say that this is a field on a Camel connector, then you mean, that this can be reused for a Syndsis _Action_, right ? (camel-connector == Syndesis Action).

So a Connection should only be offered for a position only when _some_ of the associated actions has a matching pattern. And also when the actions are listed, only the actions which are valid for this position should be shown.

BTW, for me 'pattern' is a completely misleading name. Would like 'direction' much better. 

Or something like 'kind' and then with the values `Source`, `Sink`, `SourceSink` ....

**Comment by gashcrumb** [comment]
+1 for `Source`, `Sink` and `SourceSink`, that's much easier to understand.  The data shapes should correlate to this, I guess one option is to use the presense of data shapes to figure this out too:

* `Source` -> only an output data shape
* `Sink` -> only an input data shape
* `SourceSink` -> both an output and an input data shape

This means then that a `Source` can only be used at the beginning of an integration and a `Sink` can only go at the end.

**Comment by KurtStam** [comment]
@rhuss yes synthesis action would be where we would add it. Camel calls it `pattern`. Since we don't expose this name to the enduser I'd prefer to keep it the same. 

@gashcrumb 
- `From` only in the first Step
- `To` can't be the first Step

Still not sure if it makes sense to have an `anywhere`. At the moment I think we'd make 2 actions, since the configuration options are usually different. For example a 'schedulerPeriod' for poller schedule would only make sense in a `From` action.

Data shapes somewhat correlate. It doesn't make sense to be able to input values into a `From`, I don't think we can generalize about anything else but most likely

- `From`: no input, yes output
- `To`: yes input, yes/no output

**Comment by gashcrumb** [comment]
@KurtStam it feels a little open-ended to me.  Logically I'd rather have one field to check and based on what that field is set to I know I can expect:

* `From` -> only an output data shape, can only be first
* `To` -> only an input data shape, can only be last
* `Anywhere` -> both an input and an output data shape, can be anywhere *or* can only be a middle connection, *or* ?  :-)

As these will affect mapping steps, the basic filter step etc. that rely on these data shapes to be in place, as that's all logic we have to figure out in the editor as the user adds steps to the flow.

**Comment by KurtStam** [comment]
@gashcrumb I'm not convinced we want to add dataShape into the semantics of the field tbh. I think it's possible to have `From_OUT`, `To_IN`, `To_OUT`, `To_INOUT`, `To_none`.

**Comment by gashcrumb** [comment]
@KurtStam yeah, as I think about it more I think you're right, let's forget the data shapes for a minute.  It still feels like we need 3 options, what about:

* `From` -> can only be first
* `To` -> can only be last
* `Anywhere` -> can be first, or last or in between

Or should we maybe adopt `OUT`, `IN` and `INOUT` instead?  That starts to feel more normal :-)

**Comment by KurtStam** [comment]
See also https://github.com/syndesisio/connectors/issues/7. So it looks like we are stuck with the naming. So far we only have `From` and `To`. We may never have `Both`/`Anywhere`, so I'm not going to support that until we need it. (We may never need it as we like to reduce the number of options the user can set, so in general it's better to have multiple actions so we can be more targeted with the options we offer.)

**Comment by gashcrumb** [comment]
I'm sure we'd have `Both` you can always add a connection in the middle of an integration flow, can't you?

**Comment by rhuss** [comment]
Although we are 'stuck with the name' for the connector, do we really need to repeat the same error here ? I'd prefer to have an intuitive name here and explain that it correspond to the non-intuitive name on the camel-connector instead of having two non-intuitive names.

**Comment by KurtStam** [comment]
@gashcrumb there is no such thing as 'can be last only'. `To` means anywhere except at the start. `From` means at the start only. `Anywhere` would include both, but I doubt we'll ever have a use case for that.

@rhuss sure we could map it in the synthesis data model. Kind of a pain though since we can't copy json connector configuration into our action config anyone then. IMO it would be better to keep it in sync and do a change like this in sync with the connectors.

**Comment by KurtStam** [comment]
@rhuss y I understand your concerns, however it's not like we will ever swap out Camel. So the effort to come up with our own verbiage is largely a waste of time imho, especially if we're not even showing them to the enduser. Keeping things simple wins here I think. Putting on my nomex suit now..
