### ISSUE TITLE
Tech extension : maven support

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis-rest#760]
We should create a maven plugin that leverages spring-boot-maven-plugin mojos with the following functionalities:

- [x] package an integration leveraging repackage with layout ZIP in main jar (uber jar)
- [x] package an extension leverage repackage with:
  - [x] a custom layout that put dependencies in a nested lib directory
  - [x] filter dependencies already provided by syndesis and spring boot, based on reading the corresponding BOMs:
    - https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/1.5.8.RELEASE/spring-boot-dependencies-1.5.8.RELEASE.pom
    - https://repo1.maven.org/maven2/org/apache/camel/camel-spring-boot-dependencies/2.20.0/camel-spring-boot-dependencies-2.20.0.pom
- [x] generate/update the extension metadata
  - [x] add dependencies
  - [x] support `actions`:
    - [x] reuse the definition coming from the partial `.json` file provided by the user
    - [x] auto create action scanning for specific annotations, see:
      - `kind` is a dependent field, calculated based on `target`.
      - `entrypoint` can be explicit or if missing, is the `class` of the element the annotation has been applied to
      -  https://github.com/lburgazzoli/syndesis-integration-runtime/blob/extensions/runtime-api/src/main/java/io/syndesis/integration/runtime/api/SyndesisExtensionAction.java
      - https://github.com/lburgazzoli/syndesis-project/blob/github-125-tech-extension/proposals/125-tech-extension.adoc#misc

- [x] The plugin should be named `syndesis-maven-plugin` and the existing one should be renamed to `syndesis-build-helper-maven-plugin`.

**Comment by paoloantinori** [comment]
@lburgazzoli this is still a work in progress I have to finish discussing with you: https://github.com/syndesisio/syndesis-rest/compare/master...paoloantinori:maven_plugin?expand=1

**Comment by lburgazzoli** [comment]
@paoloantinori the action descriptor field 'target' has been renamed to 'entrypoint' as it less confusing:

```json
        "descriptor": {
             "kind": "endpoint|bean|step",
             "entrypoint" : "direct:${groupId}/${artifactId}/${actionId}"
         },
```
