### ISSUE TITLE
Integration count limit is not enforced in TP2

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-rest#769]
It seems that our limits are not applied for TP2 on production cluster. Therefor I'm able to deploy 2 Integrations at once. Fortunately the current quota(after Keycloak removal) is gracious enough to accomodate those deployments.

**Comment by dsimansk** [comment]
@rhuss @zregvart correct me if I'm wrong, but we set up `annotation` during creating DC, but then fetch DCs with `label`. Could this be caused by kubernetes-client upgrade actually?

https://github.com/syndesisio/syndesis-rest/blob/bfea32ff70468911d4b7ebc3c8b29d934f8e7d6d/controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java#L116-L120


https://github.com/syndesisio/syndesis-rest/blob/bfea32ff70468911d4b7ebc3c8b29d934f8e7d6d/controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java#L194-L202

**Comment by rhuss** [comment]
Annotations and labels were and still are completely different things so I wonder whether this has changed in the code or never worked as expected. 

Let me check that later ....

**Comment by dsimansk** [comment]
As we discussed on channel, imho [the following change](https://github.com/syndesisio/syndesis-rest/compare/ca02adff...58258337#diff-e9da60db20876b6c73daa9758bf6fb50L133) is causing it. I can confirm that manually adding label `USERNAME` to first deployment prevents the subsequent one from starting and puts it immediately to `Inactive` state (without s2i build triggered etd.).
