### ISSUE TITLE
Make sure that we have replica controllers when integration pod is activated

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#784]
I've just had a restart of the rest pod as it submitted a build to openshift, after the restart build has finished and there was replica controller:

```
An error occurred while starting the deployment. Reason: replicationcontrollers "tw2sf-2" not found
```

When reworking the integration lifecycle we should make sure to check if a any definition is missing and recreate it if it is.

**Comment by jimmidyson** [comment]
We create deploymentconfigs, not replication controllers, and rely on openshift to do what's necessary to create running pods. We should be able to check the deployment for info on why RCs aren't created/updated, but we shouldn't be creating RCs ourselves.
