### ISSUE TITLE
Issue when creating new integration: NoClassDefFounfError: org/apache/commons/io/output/DeferredFileOutputStream

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis-rest#806]
I encountered an issue on the newest build of syndesis, when I tried to create a new integration:
![some_error](https://user-images.githubusercontent.com/4180208/32653359-f016e5f2-c607-11e7-8bfd-aced94c66d62.png)

In the rest-pod log you can see:
https://pastebin.com/hNWrjjkL

**Comment by dsimansk** [comment]
@zregvart any ideas? Probably some missing dep?

**Comment by zregvart** [comment]
@tplevko @dsimansk this is not in the `syndesis-qe` namespace on the dev cluster? It could be exception that has been propagated from the verifier pod, anything interesting there?

**Comment by dsimansk** [comment]
@zregvart verifier's logs are empty. It seems that request doesn't even land on verifier, the exception is thrown prior to backend->verifier call?

**Comment by zregvart** [comment]
Could caused by #788, when commons-io  was redeclared with _test_ scope

**Comment by dsimansk** [comment]
@zregvart thanks, fixed via #807.
