### ISSUE TITLE
Java dependency alignment / bom items

### ISSUE THREAD

**Issue by mattrpav** [syndesisio/syndesis-rest#90]
Tracking ticket for component alignment on Java-based dependencies and Maven plugin dependencies.

On the Data Mapper side, here are some versions we've started with. Please advise:

1. Java source+target 1.8 (Using JDK 1.8u121)
2. Maven 3.3.9
3. Maven Plugin Versions:

```
                <build-helper-maven-plugin.version>3.0.0</build-helper-maven-plugin.version>
		<maven-bundle-plugin.version>3.2.0</maven-bundle-plugin.version>
		<maven-compiler-plugin.version>3.6.1</maven-compiler-plugin.version>
		<maven-dependency-plugin.version>3.0.0</maven-dependency-plugin.version>
		<maven-deploy-plugin.version>2.8.2</maven-deploy-plugin.version>
		<maven-jar-plugin.version>3.0.2</maven-jar-plugin.version>
		<maven-jaxb2-plugin.version>0.13.1</maven-jaxb2-plugin.version>
		<jetty-maven-plugin.version>9.4.0.v20161208</jetty-maven-plugin.version>

```

4. Java dependency versions:

```
		<at.slf4j.version>1.7.22</at.slf4j.version>
		<at.jackson.version>2.8.5</at.jackson.version>
		<at.jaxb.version>2.2.12</at.jaxb.version>
		<at.junit.version>4.11</at.junit.version>
		<at.jersey.version>2.25.1</at.jersey.version>

```

Note: We found an issue with Jackson 2.8.6 not working correctly in our build process, so we are using 2.8.5 for that reason.

Outstanding questions?

1. What Camel version? Is there a Red Hat engineering build we should be referencing?  If so, please provide version and Maven Repo URL (if its an unreleased EA, tech preview, etc version)

2. What REST framework is preferred for iPaaS? We've started with Jersey, but also note that there is non-iPaaS use case out there which may drive an argument for CXF.

**Comment by davsclaus** [comment]
The Camel version will be 2.19.x. The SNAPSHOT from Apache is currently fine to use, but Red Hat are building EA builds for Fuse that are a mirror of 2.19.x and therefore we can potentially switch over to an EA build, but they only last 2 weeks before being automatic deleted.

And we aim to do a GA release of Camel 2.19.0 that iPaaS can use within the next 2 months.

**Comment by davsclaus** [comment]
What was the error with jackson 2.8.6?

**Comment by mattrpav** [comment]
We'll start using 2.19-SNAPSHOT from community to avoid the disappearing EA build issue and plan to align to the RH GA 2.19.0 when its ready.

**Comment by mattrpav** [comment]
The error with Jackson had to do with marshal/unmarshal of polymorphic objects when using certain combinations of annotations-- either standalone or through Jersey.

I just re-ran our latest code against 2.8.6 and I'm not seeing it.. aren't computers fun?

I'll retest the whole thing when we level Jackson+REST service layer.

**Comment by mattrpav** [comment]
Is there an update or an ETA at this point?

**Comment by davsclaus** [comment]
Just keep using the 2.19.0-SNAPSHOT. The plan is to release it in April
