### ISSUE TITLE
Update entity relationship diagram

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-rest#91]
Could someone kindly assist in updating one of the entity relationship diagrams that @jstrachan, @gashcrumb, and I worked on back when the API was based on Node.js? Just point out changes (not just for this sprint), additions, removals, etc. and either Stan or I will make it again. This will then be put on the iPaaS website. See below. 

I think this was the final one @gashcrumb put together after more discussion:
![entities](https://cloud.githubusercontent.com/assets/3844502/22932276/4f045a46-f295-11e6-868e-216006329cd8.png)

I think this was the original one that @jstrachan and I were starting with:
![ipaas erd](https://cloud.githubusercontent.com/assets/3844502/22932259/3ec7a52a-f295-11e6-8606-8024e67ffaf0.png)

Thanks in advance.

cc @jimmidyson @iocanel @KurtStam

**Comment by KurtStam** [comment]
@kahboom I implemented the above. It has not changed since.

**Comment by jimmidyson** [comment]
Here's a stab at a DB schema as we've discussed, just for connectors/actions at the moment. Please shoot it down or constructively tear it apart :)

![erd](https://cloud.githubusercontent.com/assets/464659/23269439/7dea6738-f9e8-11e6-83f7-d51f893a4484.png)

/cc @rhuss @iocanel @KurtStam @kahboom @gashcrumb

**Comment by gashcrumb** [comment]
@jimmidyson wonder, do we need to take into account `endpointOptions` and `componentOptions` as @davsclaus mentions [here](https://github.com/redhat-ipaas/connectors/issues/4#issuecomment-282045344) in this schema?  Or do we merge those details into one form config so it's like you have it.  In which case, does it make sense to have a field in `configuration_property` that helps distinguish if a property is for the endpoint or for the component.

**Comment by jimmidyson** [comment]
I _think_ it's OK to merge them together, don't think we really care if it's component or endpoint config. @davsclaus Can you confirm that?

**Comment by davsclaus** [comment]
Yeah we can make funktion / camel-connector be able to figure out the component vs endpoint options as it will be able to read that same json file and figure out what is what.

**Comment by rhuss** [comment]
@jimmidyson some questions, no shooting :)

* connector is `twitter`, action is `twitter_mention` right ?
* I guess that when an `action` and a `connector` reference the same `configuration_property` then the action wins ?
* Should the list of `connection_configuration_property` be ordered to aid the UI form generation ? (would require an integer `idx` in `connector_configuration_property`)
* missing some fields (if I understand correctly which is highly unlikely):
  - A reference to the Camel connector (name,class,something) in `action`
  - `hidden` field in `configuration_property`
* For an integration a user has to select the 
    - `action`,
    - the action specific configuration values (map)
    - `configured_connector` 
    There is no object / table which stores this combination for later reference (they are all referenced from the integration individually). Correct ?
* All except `configured_connector` is provided by _the system_ (== us). An expert user can modify `configuration_property` and `action_configuration_property`, though (making things hidden, changing default values, etc.)
* The relation `connector` to `configuration_property` is N:M. Could you elaborate a bit on why the same properties can be used for different connectors ?

**Comment by gashcrumb** [comment]
> Should the list of connection_configuration_property be ordered to aid the UI form generation ? (would require an integer idx in connector_configuration_property)

Yeah, good point, in fact, the expert user can arrange the form that the citizen user would see, so definitely need a way to order these.

**Comment by jimmidyson** [comment]
> connector is twitter, action is twitter_mention right ?

Correct.

> I guess that when an action and a connector reference the same configuration_property then the action wins ?

Correct.

> Should the list of connection_configuration_property be ordered to aid the UI form generation ? (would require an integer idx in connector_configuration_property)

Will add that to {connector,action}_configuration_property tables.

> missing some fields (if I understand correctly which is highly unlikely):
> A reference to the Camel connector (name,class,something) in action

Yeah. Wonder exactly what these fields should be. Are GAV coords enough? Camel endpoint prefix too perhaps?

> hidden field in configuration_property

I think we can defer this until we figure out the expert developer flow for setting this stuff. Probably required, but may not be in this table, who knows?

> For an integration a user has to select the
action,
the action specific configuration values (map)
configured_connector
There is no object / table which stores this combination for later reference (they are all referenced from the integration individually). Correct ?

Yes that was my thinking.

> All except configured_connector is provided by the system (== us). An expert user can modify configuration_property and action_configuration_property, though (making things hidden, changing default values, etc.)

We don't have Connector definition in the UX yet, just Connector Configuration (== Connection in UI AFAIK).

> The relation connector to configuration_property is N:M. Could you elaborate a bit on why the same properties can be used for different connectors ?

They can't really. This is more of a side effect of using the configuration_property table for both actions and connections. Perhaps we should have a unique keys on {connector,action}_configuration_property.configuration_property_id?

**Comment by rhuss** [comment]
Thanks @jimmidyson 

After the questions, some comments now ;)

* If a `configuration_property` either belongs to a `connector` or an `action` but can not be used for both (which I believe is the case), then I would use two separate tables: `connector_property` and `action_property`, even when they have the same columns. 
* If the relationship between an configuration_property to a connector is N:1 (that is a configuration_property belongs only to a single connector), skip the relationship table and connect it directly to the connector. Again an argument for a second `action_property` tables because here it is the same: Skip the `action_configuration_property` relationship table and use a fk to action_property.
* Instead of having 3 references to entities in this domain to be added to an integration, I would introduce two entities: `configured_action` and  `action_instance`:
  - `configured_action` : Similar to `configured_connector` but with reference to an action. This holds the action specific configuration values.
  - `action_instance`:
      + Ref to `configured_action`
      + Ref to `configured_connector`
(one could skip `configured_action` and embed the properties directly into `action_instance`, which probably makes more sense as `configured_action` is only used once for this action, no sharing required)

I consider the objects which are described here as a kind of 'micro-domain' (or bounded context), which should have exactly one transfer point: `action_instance`, which is referenced from an `intergration`.

If you think this makes somewhat sense, I could update the schema and create a diagram to make things a bit clearer.

**Comment by rhuss** [comment]
I added an alternative schema following this suggestion to https://github.com/redhat-ipaas/ipaas-rest/pull/119/commits/1b18e46d98e62a64a30ea410ec3ae0d260c37af7

**Comment by KurtStam** [comment]
![page 1](https://cloud.githubusercontent.com/assets/35576/23282331/a835ca7c-f9ee-11e6-88aa-0f64e147543f.png)

![page 2](https://cloud.githubusercontent.com/assets/35576/23282351/c42b6700-f9ee-11e6-8d35-62cdccb4c1b4.png)

![page 3](https://cloud.githubusercontent.com/assets/35576/23282354/c7f55a62-f9ee-11e6-8df8-68f2e5854d75.png)

**Comment by rhuss** [comment]
For reference, the revised diagram from #119 : 

![schema](https://cloud.githubusercontent.com/assets/99080/23305368/c0ab0472-fa9e-11e6-86c3-e91f21eee70d.png)

**Comment by KurtStam** [comment]
These are the models we based the model2 module on. If we want to go relational we may want to keep this, if we want to stick to JSONDB then we can probably delete the model2 module and close this.
